---
title: "Dissertaion GPT Figure"
subtitle: "Bacher Group" 
date: today
date-format: long
author:
  - name: Jack R. Leary
    orcid: 0009-0004-8821-3269
    email: j.leary@ufl.edu
    corresponding: true
    affiliation: 
      - name: University of Florida
        department: Department of Biostatistics
        city: Gainesville
        state: FL
        country: US
format:
  html: 
    theme: journal
    highlight-style: tango
    toc: true
    toc-depth: 2
    toc-location: left
    code-copy: hover
    code-tools: true
    code-fold: show
    embed-resources: true
    number-sections: true
    fig-width: 6
    fig-height: 4
    fig-dpi: 320
    fig-align: center
    fig-cap-location: bottom
    tbl-cap-location: bottom
editor: source
---

```{r setup}
#| echo: false
#| include: false
#| message: false
#| warning: false
knitr::opts_chunk$set(comment = NA)
options(future.globals.maxSize = 1e20)
reticulate::use_virtualenv("../../.venv")
```

# Libraries 

We begin by reading in some necessary libraries for our analysis. 

```{r}
#| message: false
#| warning: false
#| results: hide
library(dplyr)
library(hdf5r)
library(Seurat)
library(bayesVG)
library(ggplot2)
library(anndata)
library(patchwork)
library(reticulate)
rename <- dplyr::rename
```

# Visualization tools

Next, we define a set of color palettes to be used for our plots. 

```{r}
palette_domain <- paletteer::paletteer_d("ggsci::nrc_npg")
palette_heatmap <- paletteer::paletteer_d("MetBrewer::Hiroshige", direction = -1)
```

We also define a custom legend guide to be used when plotting UMAP embeddings. 

```{r}
guide_umap <- function(key.size = 4) {
  ggplot2::guides(color = ggplot2::guide_legend(override.aes = list(size = key.size,
                                                                    alpha = 1, 
                                                                    stroke = 1)))
}
```

# Data 

## Python pre-processing

### Libraries

```{python}
#| eval: false
import numpy as np
import scanpy as sc
import pandas as pd
import anndata as ad
import squidpy as sq
```

### Load data 

```{r}
ad_brain <- read_h5ad("../../data/human-brain-spatial/ad_brain.h5ad")
```



```{r}
counts_mtx <- as.matrix(ad_brain$layers["counts"])
counts_mtx <- as(counts_mtx, "CsparseMatrix")
seu_brain <- CreateSeuratObject(t(counts_mtx), 
                                assay = "Spatial",
                                meta.data = as.data.frame(ad_brain$obs),
                                min.cells = 0, 
                                min.features = 0)
seu_brain@project.name <- "cortex"
seu_brain <- NormalizeData(seu_brain, 
                           assay = "Spatial", 
                           verbose = FALSE)
```

```{r}
pca_embed <- ad_brain$obsm$X_pca
rownames(pca_embed) <- ad_brain$obs_names
colnames(pca_embed) <- paste0("PC_", seq(50))
pca_embed <- CreateDimReducObject(pca_embed, 
                                  assay = "Spatial", 
                                  key = "pca_", 
                                  global = TRUE)
seu_brain@reductions$pca <- pca_embed
```


```{r}
umap_embed <- ad_brain$obsm$X_umap
rownames(umap_embed) <- ad_brain$obs_names
colnames(umap_embed) <- c("UMAP_1", "UMAP_2")
umap_embed <- CreateDimReducObject(umap_embed, 
                                   assay = "Spatial", 
                                   key = "umap_", 
                                   global = TRUE)
seu_brain@reductions$umap <- umap_embed
```


Now for the tricky part - adding in the image data. 

```{r}
coord_df <- data.frame(imagecol = ad_brain$obsm$spatial[, 1], 
                       imagerow = ad_brain$obsm$spatial[, 2])
rownames(coord_df) = ad_brain$obs_names
img_array <- ad_brain$uns$spatial$V1_Human_Brain_Section_1$images$lowres
fiducial_diameter <- ad_brain$uns$spatial$V1_Human_Brain_Section_1$scalefactors$fiducial_diameter_fullres
lores_sf <- ad_brain$uns$spatial$V1_Human_Brain_Section_1$scalefactors$tissue_lowres_scalef
spot_radius <- (fiducial_diameter * lores_sf) / max(dim(img_array))
hires_sf <- ad_brain$uns$spatial$V1_Human_Brain_Section_1$scalefactors$tissue_hires_scalef
spot_diameter <- ad_brain$uns$spatial$V1_Human_Brain_Section_1$scalefactors$spot_diameter_fullres
seu_brain@images[["cortex"]] <- new(Class = "VisiumV1",
                                    assay = "Spatial", 
                                    image = img_array, 
                                    key = "image_", 
                                    coordinates = coord_df, 
                                    scale.factors = scalefactors(spot = spot_diameter, 
                                                                 fiducial = fiducial_diameter, 
                                                                 hires = hires_sf, 
                                                                 lowres = lores_sf), 
                                    spot.radius = spot_radius)
```

```{r}
#| fig-width: 3.3
#| fig-height: 3
#| fig-dpi: 200
p0 <- plotSpatialAttributes(seu_brain, 
                            attribute.plot = "leiden", 
                            pt.size = 1, 
                            color.palette = palette_domain) + 
      labs(color = "Leiden") + 
      theme_bayesVG(base.size = 8, spatial = TRUE) + 
      guide_umap(key.size = 3)
p0
```

```{r}
ggsave("brain_spatial_scatter.pdf", 
       plot = p0, 
       device = "pdf", 
       path = "../pdf/",
       width = 3.3, 
       height = 3, 
       units = "in")
```

```{r}
#| fig-width: 4
#| fig-height: 3
#| fig-dpi: 200
umap_df <- data.frame(umap1 = seu_brain@reductions$umap@cell.embeddings[, 1], 
                      umap2 = seu_brain@reductions$umap@cell.embeddings[, 2], 
                      leiden = seu_brain$leiden)
p1 <- ggplot(umap_df, aes(x = umap1, y = umap2, color = leiden)) + 
      geom_point(size = 1.5, alpha = 0.8, stroke = 0) + 
      scale_color_manual(values = palette_domain) + 
      labs(x = "UMAP 1", y = "UMAP 2") + 
      theme_bayesVG(base.size = 8, umap = TRUE) + 
      theme(legend.position = "none")
p1
```

```{r}
ggsave("brain_umap_scatter.pdf", 
       plot = p1, 
       device = "pdf", 
       path = "../pdf/",
       width = 4, 
       height = 3, 
       units = "in")
```

```{r}
#| fig-width: 4.3
#| fig-height: 4
#| fig-dpi: 200
moran_df <- ad_brain$uns$moranI
top4_svgs <- slice_head(moran_df, n = 4) %>% 
             rownames()
expr_df <- GetAssayData(seu_brain, assay = "Spatial", layer = "data")[top4_svgs, ] %>% 
           t() %>% 
           as.data.frame() %>% 
           mutate(spot = rownames(.), 
                  x = GetTissueCoordinates(seu_brain)[, 1], 
                  y = GetTissueCoordinates(seu_brain)[, 2],
                  .before = 1) %>% 
           tidyr::pivot_longer(cols = !c(spot, x, y),  
                               names_to = "gene", 
                               values_to = "gene_expression") %>% 
           mutate(gene_expression = coop::scaler(gene_expression))
p2 <- ggplot(expr_df, aes(x = x, y = y, color = gene_expression)) + 
      facet_wrap(~gene, nrow = 2, ncol = 2) + 
      geom_point(size = 0.75, stroke = 0) + 
      scale_y_continuous(transform = "reverse") + 
      scale_color_gradientn(colors = palette_heatmap) + 
      labs(x = "Spatial 1", 
           y = "Spatial 2", 
           color = "Scaled\nExpression") + 
      theme_bayesVG(base.size = 8, spatial = TRUE) +
      theme(strip.text = element_text(face = "italic"), 
            strip.clip = "on", 
            strip.background = element_rect(linewidth = 2 * theme_bayesVG()$line$linewidth))
p2
```

```{r}
ggsave("brain_svg_expression_scatter.pdf", 
       plot = p2, 
       device = "pdf", 
       path = "../pdf/",
       width = 4.3, 
       height = 4, 
       units = "in")
```

```{r}
#| fig-width: 3
#| fig-height: 4
#| fig-dpi: 200
svg_clust_df <- data.frame(svg_cluster0 = seu_brain$svg_cluster0, 
                           svg_cluster1 = seu_brain$svg_cluster1) %>% 
                bind_cols(GetTissueCoordinates(seu_brain))
p3 <- ggplot(svg_clust_df, aes(x = imagerow, y = imagecol, color = svg_cluster0)) + 
      geom_point(size = 0.75, stroke = 0, alpha = 1) + 
      scale_y_continuous(transform = "reverse") + 
      scale_color_gradientn(colors = palette_heatmap) + 
      labs(x = "Spatial 1", 
           y = "Spatial 2", 
           color = "Module 0") + 
      theme_bayesVG(base.size = 8, spatial = TRUE)
p4 <- ggplot(svg_clust_df, aes(x = imagerow, y = imagecol, color = svg_cluster1)) + 
      geom_point(size = 0.75, stroke = 0, alpha = 1) + 
      scale_y_continuous(transform = "reverse") + 
      scale_color_gradientn(colors = palette_heatmap) + 
      labs(x = "Spatial 1", 
           y = "Spatial 2", 
           color = "Module 1") + 
      theme_bayesVG(base.size = 8, spatial = TRUE)
p5 <- (p3 / p4) + plot_layout(axes = "collect")
p5
```

```{r}
ggsave("brain_svg_module_scatter.pdf", 
       plot = p5, 
       device = "pdf", 
       path = "../pdf/",
       width = 3, 
       height = 4, 
       units = "in")
```
